# .github/workflows/lighthouse-ci.yml
name: Shopify Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@1.0
        with:
          lhci_min_score_performance: 0.8
          lhci_min_score_accessibility: 0.9
          store: '${{ secrets.SHOP_STORE }}'
          app_id: '${{ secrets.SHOP_APP_ID }}'
          app_password: '${{ secrets.SHOP_APP_PASSWORD }}'
          password: '${{ secrets.SHOP_PASSWORD }}'
